# Site settings
title: seaven简简单单
email: xiushiwen001@163.com
description: > # this means to ignore newlines until "baseurl:"
  记录,学习,点点滴滴.
baseurl: "/xiusw.github.io"
url: "http://xiushiwen.github.io/xiusw.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  xiushiwen

# Build settings
markdown: kramdown
